// 20220310171420
// http://localhost:8080/v3/api-docs

{
  "openapi": "3.0.1",
  "info": {
    "title": "Blog Pessoal",
    "description": "Project Personal Blog - Generation Brazil",
    "contact": {
      "name": "Victor Costa",
      "url": "https://github.com/Matth998/DumbledoreArmy",
      "email": "costavictor771@gmail.com"
    },
    "license": {
      "name": "generation.org.br",
      "url": "http://springdoc.org"
    },
    "version": "v1.0.0"
  },
  "externalDocs": {
    "description": "Github",
    "url": "https://github.com/victorcosta1"
  },
  "servers": [
    {
      "url": "http://localhost:8080",
      "description": "Generated server url"
    }
  ],
  "paths": {
    "/user/update": {
      "put": {
        "tags": [
          "user-controller"
        ],
        "operationId": "putUsuario",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserModel"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Sucess!"
          },
          "201": {
            "description": "Persistent Object!"
          },
          "204": {
            "description": "Deleted Object!"
          },
          "400": {
            "description": "Error in the Request!"
          },
          "401": {
            "description": "Unauthorized access!"
          },
          "404": {
            "description": "Object not found!"
          },
          "500": {
            "description": "Application Error!"
          }
        }
      }
    },
    "/theme": {
      "get": {
        "tags": [
          "theme-controller"
        ],
        "operationId": "getAll_1",
        "responses": {
          "200": {
            "description": "Sucess!"
          },
          "201": {
            "description": "Persistent Object!"
          },
          "204": {
            "description": "Deleted Object!"
          },
          "400": {
            "description": "Error in the Request!"
          },
          "401": {
            "description": "Unauthorized access!"
          },
          "404": {
            "description": "Object not found!"
          },
          "500": {
            "description": "Application Error!"
          }
        }
      },
      "put": {
        "tags": [
          "theme-controller"
        ],
        "operationId": "put",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ThemeModel"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Sucess!"
          },
          "201": {
            "description": "Persistent Object!"
          },
          "204": {
            "description": "Deleted Object!"
          },
          "400": {
            "description": "Error in the Request!"
          },
          "401": {
            "description": "Unauthorized access!"
          },
          "404": {
            "description": "Object not found!"
          },
          "500": {
            "description": "Application Error!"
          }
        }
      },
      "post": {
        "tags": [
          "theme-controller"
        ],
        "operationId": "post",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ThemeModel"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Sucess!"
          },
          "201": {
            "description": "Persistent Object!"
          },
          "204": {
            "description": "Deleted Object!"
          },
          "400": {
            "description": "Error in the Request!"
          },
          "401": {
            "description": "Unauthorized access!"
          },
          "404": {
            "description": "Object not found!"
          },
          "500": {
            "description": "Application Error!"
          }
        }
      }
    },
    "/post": {
      "get": {
        "tags": [
          "post-controller"
        ],
        "operationId": "GetAll",
        "responses": {
          "200": {
            "description": "Sucess!"
          },
          "201": {
            "description": "Persistent Object!"
          },
          "204": {
            "description": "Deleted Object!"
          },
          "400": {
            "description": "Error in the Request!"
          },
          "401": {
            "description": "Unauthorized access!"
          },
          "404": {
            "description": "Object not found!"
          },
          "500": {
            "description": "Application Error!"
          }
        }
      },
      "put": {
        "tags": [
          "post-controller"
        ],
        "operationId": "putBody",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/PostModel"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Sucess!"
          },
          "201": {
            "description": "Persistent Object!"
          },
          "204": {
            "description": "Deleted Object!"
          },
          "400": {
            "description": "Error in the Request!"
          },
          "401": {
            "description": "Unauthorized access!"
          },
          "404": {
            "description": "Object not found!"
          },
          "500": {
            "description": "Application Error!"
          }
        }
      },
      "post": {
        "tags": [
          "post-controller"
        ],
        "operationId": "postBody",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/PostModel"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Sucess!"
          },
          "201": {
            "description": "Persistent Object!"
          },
          "204": {
            "description": "Deleted Object!"
          },
          "400": {
            "description": "Error in the Request!"
          },
          "401": {
            "description": "Unauthorized access!"
          },
          "404": {
            "description": "Object not found!"
          },
          "500": {
            "description": "Application Error!"
          }
        }
      }
    },
    "/user/register": {
      "post": {
        "tags": [
          "user-controller"
        ],
        "operationId": "postUsuario",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserModel"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Sucess!"
          },
          "201": {
            "description": "Persistent Object!"
          },
          "204": {
            "description": "Deleted Object!"
          },
          "400": {
            "description": "Error in the Request!"
          },
          "401": {
            "description": "Unauthorized access!"
          },
          "404": {
            "description": "Object not found!"
          },
          "500": {
            "description": "Application Error!"
          }
        }
      }
    },
    "/user/login": {
      "post": {
        "tags": [
          "user-controller"
        ],
        "operationId": "login",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserLogin"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Sucess!"
          },
          "201": {
            "description": "Persistent Object!"
          },
          "204": {
            "description": "Deleted Object!"
          },
          "400": {
            "description": "Error in the Request!"
          },
          "401": {
            "description": "Unauthorized access!"
          },
          "404": {
            "description": "Object not found!"
          },
          "500": {
            "description": "Application Error!"
          }
        }
      }
    },
    "/user/{id}": {
      "get": {
        "tags": [
          "user-controller"
        ],
        "operationId": "getById",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Sucess!"
          },
          "201": {
            "description": "Persistent Object!"
          },
          "204": {
            "description": "Deleted Object!"
          },
          "400": {
            "description": "Error in the Request!"
          },
          "401": {
            "description": "Unauthorized access!"
          },
          "404": {
            "description": "Object not found!"
          },
          "500": {
            "description": "Application Error!"
          }
        }
      }
    },
    "/user/all": {
      "get": {
        "tags": [
          "user-controller"
        ],
        "operationId": "getAll",
        "responses": {
          "200": {
            "description": "Sucess!"
          },
          "201": {
            "description": "Persistent Object!"
          },
          "204": {
            "description": "Deleted Object!"
          },
          "400": {
            "description": "Error in the Request!"
          },
          "401": {
            "description": "Unauthorized access!"
          },
          "404": {
            "description": "Object not found!"
          },
          "500": {
            "description": "Application Error!"
          }
        }
      }
    },
    "/theme/{id}": {
      "get": {
        "tags": [
          "theme-controller"
        ],
        "operationId": "getById_1",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Sucess!"
          },
          "201": {
            "description": "Persistent Object!"
          },
          "204": {
            "description": "Deleted Object!"
          },
          "400": {
            "description": "Error in the Request!"
          },
          "401": {
            "description": "Unauthorized access!"
          },
          "404": {
            "description": "Object not found!"
          },
          "500": {
            "description": "Application Error!"
          }
        }
      },
      "delete": {
        "tags": [
          "theme-controller"
        ],
        "operationId": "delete",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Sucess!"
          },
          "201": {
            "description": "Persistent Object!"
          },
          "204": {
            "description": "Deleted Object!"
          },
          "400": {
            "description": "Error in the Request!"
          },
          "401": {
            "description": "Unauthorized access!"
          },
          "404": {
            "description": "Object not found!"
          },
          "500": {
            "description": "Application Error!"
          }
        }
      }
    },
    "/theme/name/{name}": {
      "get": {
        "tags": [
          "theme-controller"
        ],
        "operationId": "getByName",
        "parameters": [
          {
            "name": "name",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Sucess!"
          },
          "201": {
            "description": "Persistent Object!"
          },
          "204": {
            "description": "Deleted Object!"
          },
          "400": {
            "description": "Error in the Request!"
          },
          "401": {
            "description": "Unauthorized access!"
          },
          "404": {
            "description": "Object not found!"
          },
          "500": {
            "description": "Application Error!"
          }
        }
      }
    },
    "/post/{id}": {
      "get": {
        "tags": [
          "post-controller"
        ],
        "operationId": "GetById",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Sucess!"
          },
          "201": {
            "description": "Persistent Object!"
          },
          "204": {
            "description": "Deleted Object!"
          },
          "400": {
            "description": "Error in the Request!"
          },
          "401": {
            "description": "Unauthorized access!"
          },
          "404": {
            "description": "Object not found!"
          },
          "500": {
            "description": "Application Error!"
          }
        }
      },
      "delete": {
        "tags": [
          "post-controller"
        ],
        "operationId": "delete_1",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Sucess!"
          },
          "201": {
            "description": "Persistent Object!"
          },
          "204": {
            "description": "Deleted Object!"
          },
          "400": {
            "description": "Error in the Request!"
          },
          "401": {
            "description": "Unauthorized access!"
          },
          "404": {
            "description": "Object not found!"
          },
          "500": {
            "description": "Application Error!"
          }
        }
      }
    },
    "/post/title/{title}": {
      "get": {
        "tags": [
          "post-controller"
        ],
        "operationId": "GetByTitle",
        "parameters": [
          {
            "name": "title",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Sucess!"
          },
          "201": {
            "description": "Persistent Object!"
          },
          "204": {
            "description": "Deleted Object!"
          },
          "400": {
            "description": "Error in the Request!"
          },
          "401": {
            "description": "Unauthorized access!"
          },
          "404": {
            "description": "Object not found!"
          },
          "500": {
            "description": "Application Error!"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "PostModel": {
        "required": [
          "description",
          "title"
        ],
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64"
          },
          "title": {
            "maxLength": 100,
            "minLength": 4,
            "type": "string"
          },
          "description": {
            "maxLength": 500,
            "minLength": 10,
            "type": "string"
          },
          "date": {
            "type": "string",
            "format": "date-time"
          },
          "theme": {
            "$ref": "#/components/schemas/ThemeModel"
          },
          "user": {
            "$ref": "#/components/schemas/UserModel"
          }
        }
      },
      "ThemeModel": {
        "required": [
          "description"
        ],
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64"
          },
          "description": {
            "maxLength": 100,
            "minLength": 4,
            "type": "string"
          }
        }
      },
      "UserModel": {
        "required": [
          "name",
          "password",
          "user"
        ],
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64"
          },
          "name": {
            "type": "string"
          },
          "user": {
            "type": "string",
            "example": "email@dominio.com"
          },
          "password": {
            "maxLength": 2147483647,
            "minLength": 8,
            "type": "string"
          },
          "photo": {
            "type": "string"
          },
          "postagem": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/PostModel"
            }
          }
        }
      },
      "UserLogin": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64"
          },
          "name": {
            "type": "string"
          },
          "user": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "photo": {
            "type": "string"
          },
          "token": {
            "type": "string"
          }
        }
      }
    }
  }
}